module.exports = {
  paddingCssProps: {
    paddingLeft: {
      index: 64,
      group: "Padding",
      default: 0,
      applyDefault: false,
      displayName: "Pad Left",
      type: {
        name: "number",
        units: ["px"],
        defaultUnit: "px",
        marginPaddingComp: "padding-left",
      },
      allowVisualStates: true,
    },
    paddingRight: {
      index: 65,
      group: "Padding",
      default: 0,
      applyDefault: false,
      displayName: "Pad Right",
      type: {
        name: "number",
        units: ["px"],
        defaultUnit: "px",
        marginPaddingComp: "padding-right",
      },
      allowVisualStates: true,
    },
    paddingTop: {
      index: 66,
      group: "Padding",
      displayName: "Pad Top",
      default: 0,
      applyDefault: false,
      type: {
        name: "number",
        units: ["px"],
        defaultUnit: "px",
        marginPaddingComp: "padding-top",
      },
      allowVisualStates: true,
    },
    paddingBottom: {
      index: 67,
      group: "Padding",
      displayName: "Pad Bottom",
      default: 0,
      applyDefault: false,
      type: {
        name: "number",
        units: ["px"],
        defaultUnit: "px",
        marginPaddingComp: "padding-bottom",
      },
      allowVisualStates: true,
    },
  },
  boxShadowProps: {
    boxShadowEnabled: {
      index: 250,
      group: "Box Shadow",
      displayName: "Shadow Enabled",
      type: "boolean",
      default: false,
    },
    boxShadowOffsetX: {
      index: 251,
      group: "Box Shadow",
      displayName: "Offset X",
      default: 0,
      type: {
        name: "number",
        units: ["px"],
        defaultUnit: "px",
      },
    },
    boxShadowOffsetY: {
      index: 252,
      group: "Box Shadow",
      displayName: "Offset Y",
      default: 0,
      type: {
        name: "number",
        units: ["px"],
        defaultUnit: "px",
      },
    },
    boxShadowBlurRadius: {
      index: 253,
      group: "Box Shadow",
      displayName: "Blur Radius",
      default: 5,
      type: {
        name: "number",
        units: ["px"],
        defaultUnit: "px",
      },
    },
    boxShadowSpreadRadius: {
      index: 254,
      group: "Box Shadow",
      displayName: "Spread Radius",
      default: 2,
      type: {
        name: "number",
        units: ["px"],
        defaultUnit: "px",
      },
    },
    boxShadowInset: {
      index: 255,
      group: "Box Shadow",
      displayName: "Inset",
      type: "boolean",
      default: false,
    },
    boxShadowColor: {
      index: 256,
      group: "Box Shadow",
      displayName: "Shadow Color",
      type: "color",
      default: "rgba(0,0,0,0.2)",
    },
  },
};
